name: cv_maker
description: CV oluşturma ve paylaşma uygulaması.

# Uygulama versiyonu
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI bileşenleri
  cupertino_icons: ^1.0.5
  webview_flutter: ^4.2.2
  flutter_native_splash: ^2.3.1
  
  # Durum yönetimi
  provider: ^6.0.5
  
  # Dosya işlemleri
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.0.15
  # flutter_html_to_pdf: ^0.7.0
  
  # Paylaşım ve depolama
  share_plus: ^7.0.2
  shared_preferences: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  # Uygulamada kullanılacak görseller
  assets:
    - assets/modern_template.png
    - assets/classic_template.png
    - assets/minimalist_template.png
    - assets/app_logo.png
  
  

# Flutter Native Splash ekranı yapılandırması
flutter_native_splash:
  color: "#2C3E50"
  image: assets/app_logo.png
  android: true
  ios: true